import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

const root = new URL("../", import.meta.url);
const contractUrl = new URL("packages/contracts/openapi.yaml", root);
const baselineUrl = new URL("packages/contracts/baseline/openapi.json", root);
const outputUrl = new URL("packages/contracts/src/generated/index.mjs", root);

function stableJson(value) {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

export async function readContract(url = contractUrl) {
  const source = await readFile(url, "utf8");
  return JSON.parse(source);
}

function requiredFields(schema) {
  return new Set(schema?.required ?? []);
}

export function assertBackwardCompatible(baseline, candidate) {
  const failures = [];
  const baselineSchemas = baseline.components?.schemas ?? {};
  const candidateSchemas = candidate.components?.schemas ?? {};

  for (const [schemaName, baselineSchema] of Object.entries(baselineSchemas)) {
    const candidateSchema = candidateSchemas[schemaName];
    if (!candidateSchema) {
      failures.push(`${schemaName}: schema removed`);
      continue;
    }
    const candidateRequired = requiredFields(candidateSchema);
    for (const field of requiredFields(baselineSchema)) {
      if (!candidateSchema.properties?.[field]) {
        failures.push(`${schemaName}.${field}: property removed`);
      } else if (!candidateRequired.has(field)) {
        failures.push(`${schemaName}.${field}: required response field removed`);
      }
    }
  }

  for (const [path, baselinePath] of Object.entries(baseline.paths ?? {})) {
    const candidatePath = candidate.paths?.[path];
    if (!candidatePath) {
      failures.push(`${path}: path removed`);
      continue;
    }
    for (const method of Object.keys(baselinePath)) {
      if (!candidatePath[method]) {
        failures.push(`${method.toUpperCase()} ${path}: operation removed`);
      }
    }
  }

  if (failures.length > 0) {
    throw new Error(`Breaking OpenAPI changes detected:\n${failures.join("\n")}`);
  }
}

export function generateClientSource(contract) {
  const hash = createHash("sha256").update(stableJson(contract)).digest("hex");
  return `// Generated by scripts/generate-client.mjs. Do not edit.
// OpenAPI SHA-256: ${hash}

/** @typedef {{ id: string, date: string }} ExampleResource */
/** @typedef {{ code: string, label: string, aliases?: string[], icon?: string, color?: string, lineStyle?: string }} ReferenceEntry */
/** @typedef {{ currencies: ReferenceEntry[], costCategories: ReferenceEntry[], transportModes: ReferenceEntry[], currencyAliases: Record<string, string> }} ReferenceData */
/** @typedef {{ field: string, message: string }} FieldError */
/** @typedef {{ type: string, title: string, status: number, code: string, traceId: string, errors: FieldError[], detail?: string, instance?: string }} ProblemDetails */

export const generatedOpenApiSha256 = "${hash}";

/** @param {unknown} value @param {string} name @returns {Record<string, unknown>} */
function asObject(value, name) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(\`\${name} must be an object\`);
  }
  return /** @type {Record<string, unknown>} */ (value);
}

/** @param {unknown} value @returns {ExampleResource} */
export function parseExampleResponse(value) {
  const object = asObject(value, "ExampleResource");
  if (typeof object.id !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(object.id)) {
    throw new TypeError("ExampleResource.id must be a UUID");
  }
  if (typeof object.date !== "string" || !/^\\d{4}-\\d{2}-\\d{2}$/u.test(object.date)) {
    throw new TypeError("ExampleResource.date must be YYYY-MM-DD");
  }
  return { id: object.id, date: object.date };
}

/** @param {unknown} value @returns {ReferenceData} */
export function parseReferenceDataResponse(value) {
  const object = asObject(value, "ReferenceData");
  /** @param {unknown} entries @param {string} name @param {boolean} visual */
  const parseEntries = (entries, name, visual) => {
    if (!Array.isArray(entries)) throw new TypeError(\`\${name} must be an array\`);
    return entries.map((entry) => {
      const parsed = asObject(entry, \`\${name} entry\`);
      if (typeof parsed.code !== "string" || typeof parsed.label !== "string") {
        throw new TypeError(\`\${name} code and label must be strings\`);
      }
      if (parsed.aliases !== undefined && (!Array.isArray(parsed.aliases) || parsed.aliases.some((alias) => typeof alias !== "string"))) {
        throw new TypeError(\`\${name} aliases must be strings\`);
      }
      if (visual && (typeof parsed.icon !== "string" || !/^#[0-9A-F]{6}$/u.test(String(parsed.color)))) {
        throw new TypeError(\`\${name} visual fields are invalid\`);
      }
      if (name === "transportModes" && !["solid", "dashed", "dotted"].includes(String(parsed.lineStyle))) {
        throw new TypeError("transportModes lineStyle is invalid");
      }
      return {
        code: parsed.code,
        label: parsed.label,
        ...(Array.isArray(parsed.aliases) ? { aliases: /** @type {string[]} */ (parsed.aliases) } : {}),
        ...(typeof parsed.icon === "string" ? { icon: parsed.icon } : {}),
        ...(typeof parsed.color === "string" ? { color: parsed.color } : {}),
        ...(typeof parsed.lineStyle === "string" ? { lineStyle: parsed.lineStyle } : {}),
      };
    });
  };
  const aliases = asObject(object.currencyAliases, "currencyAliases");
  if (Object.values(aliases).some((alias) => typeof alias !== "string")) {
    throw new TypeError("currencyAliases values must be strings");
  }
  return {
    currencies: parseEntries(object.currencies, "currencies", false),
    costCategories: parseEntries(object.costCategories, "costCategories", true),
    transportModes: parseEntries(object.transportModes, "transportModes", true),
    currencyAliases: /** @type {Record<string, string>} */ (aliases),
  };
}

/** @param {unknown} value @returns {ProblemDetails} */
export function parseProblemDetails(value) {
  const object = asObject(value, "ProblemDetails");
  for (const field of ["type", "title", "code", "traceId"]) {
    if (typeof object[field] !== "string" || object[field].length === 0) {
      throw new TypeError(\`ProblemDetails.\${field} must be a non-empty string\`);
    }
  }
  if (!Number.isInteger(object.status) || typeof object.status !== "number" || object.status < 400 || object.status > 599) {
    throw new TypeError("ProblemDetails.status must be an HTTP error status");
  }
  if (!Array.isArray(object.errors)) {
    throw new TypeError("ProblemDetails.errors must be an array");
  }
  return {
    type: /** @type {string} */ (object.type),
    title: /** @type {string} */ (object.title),
    status: object.status,
    code: /** @type {string} */ (object.code),
    traceId: /** @type {string} */ (object.traceId),
    errors: object.errors.map((error) => {
      const fieldError = asObject(error, "FieldError");
      if (typeof fieldError.field !== "string" || typeof fieldError.message !== "string") {
        throw new TypeError("FieldError fields must be strings");
      }
      return { field: fieldError.field, message: fieldError.message };
    }),
    ...(typeof object.detail === "string" ? { detail: object.detail } : {}),
    ...(typeof object.instance === "string" ? { instance: object.instance } : {}),
  };
}

export class ApiProblemError extends Error {
  /** @param {ProblemDetails} problem */
  constructor(problem) {
    super(problem.title);
    this.name = "ApiProblemError";
    this.problem = problem;
  }
}

export class OnTheRoadClient {
  /** @param {string} baseUrl @param {{ fetch?: typeof fetch }} [options] */
  constructor(baseUrl, options = {}) {
    this.baseUrl = baseUrl.replace(/\\/$/u, "");
    this.fetch = options.fetch ?? globalThis.fetch;
  }

  /** @param {string} [exampleId] @returns {Promise<{ data: ExampleResource, etag: string | null }>} */
  async getExample(exampleId) {
    const suffix = exampleId ? \`/example/\${encodeURIComponent(exampleId)}\` : "/example";
    const response = await this.fetch(\`\${this.baseUrl}/api/v1\${suffix}\`, {
      headers: { accept: "application/json, application/problem+json" },
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new ApiProblemError(parseProblemDetails(payload));
    }
    return { data: parseExampleResponse(payload), etag: response.headers.get("etag") };
  }

  /** @returns {Promise<{ data: ReferenceData }>} */
  async getReferenceData() {
    const response = await this.fetch(\`\${this.baseUrl}/api/v1/system/reference-data\`, {
      headers: { accept: "application/json, application/problem+json" },
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new ApiProblemError(parseProblemDetails(payload));
    }
    return { data: parseReferenceDataResponse(payload) };
  }
}
`;
}

async function main() {
  const contract = await readContract();
  const baseline = await readContract(baselineUrl);
  assertBackwardCompatible(baseline, contract);
  const generated = generateClientSource(contract);

  if (process.argv.includes("--check")) {
    const committed = await readFile(outputUrl, "utf8");
    if (committed !== generated) {
      throw new Error("Generated client is stale. Run `pnpm --filter @on-the-road/contracts generate`.");
    }
    return;
  }
  await writeFile(outputUrl, generated);
}

const invokedPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : "";
if (import.meta.url === invokedPath) {
  await main();
}
