import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

const root = new URL("../", import.meta.url);
const contractUrl = new URL("packages/contracts/openapi.yaml", root);
const baselineUrl = new URL("packages/contracts/baseline/openapi.json", root);
const outputUrl = new URL("packages/contracts/src/generated/index.mjs", root);

function stableJson(value) {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

export async function readContract(url = contractUrl) {
  const source = await readFile(url, "utf8");
  return JSON.parse(source);
}

function requiredFields(schema) {
  return new Set(schema?.required ?? []);
}

export function assertBackwardCompatible(baseline, candidate) {
  const failures = [];
  const baselineSchemas = baseline.components?.schemas ?? {};
  const candidateSchemas = candidate.components?.schemas ?? {};

  for (const [schemaName, baselineSchema] of Object.entries(baselineSchemas)) {
    const candidateSchema = candidateSchemas[schemaName];
    if (!candidateSchema) {
      failures.push(`${schemaName}: schema removed`);
      continue;
    }
    const candidateRequired = requiredFields(candidateSchema);
    for (const field of requiredFields(baselineSchema)) {
      if (!candidateSchema.properties?.[field]) {
        failures.push(`${schemaName}.${field}: property removed`);
      } else if (!candidateRequired.has(field)) {
        failures.push(`${schemaName}.${field}: required response field removed`);
      }
    }
  }

  for (const [path, baselinePath] of Object.entries(baseline.paths ?? {})) {
    const candidatePath = candidate.paths?.[path];
    if (!candidatePath) {
      failures.push(`${path}: path removed`);
      continue;
    }
    for (const method of Object.keys(baselinePath)) {
      if (!candidatePath[method]) {
        failures.push(`${method.toUpperCase()} ${path}: operation removed`);
      }
    }
  }

  if (failures.length > 0) {
    throw new Error(`Breaking OpenAPI changes detected:\n${failures.join("\n")}`);
  }
}

export function generateClientSource(contract) {
  const hash = createHash("sha256").update(stableJson(contract)).digest("hex");
  return `// Generated by scripts/generate-client.mjs. Do not edit.
// OpenAPI SHA-256: ${hash}

/** @typedef {{ id: string, date: string }} ExampleResource */
/** @typedef {{ id: string, name: string, countryCode: string | null, city: string | null, region: string | null, sortOrder: number, createdAt: string, updatedAt: string }} Destination */
/** @typedef {{ id: string, ownerId: string, name: string, startDate: string, endDate: string, totalDays: number, travelers: number, defaultCurrency: string, budget: string | null, timezone: string, mapProfile: "cn_primary" | "international_primary" | "hybrid", description: string | null, status: "draft" | "active" | "archived" | "deleted", version: number, createdAt: string, updatedAt: string, deletedAt: string | null, destinations: Destination[] }} Trip */
/** @typedef {{ items: Trip[], nextCursor: string | null }} TripPage */
/** @typedef {{ id: string, tripId: string, ownerId: string, tripDayId: string, itemType: "activity" | "attraction" | "dining" | "hotel" | "transport" | "other", timeKind: "clock" | "range" | "period" | "unscheduled", startTime: string | null, endTime: string | null, endDayOffset: 0 | 1, timeZone: string | null, timePeriod: string | null, target: string | null, description: string | null, durationMinutes: number | null, destinationId: string | null, locationId: string | null, startLocationId: string | null, endLocationId: string | null, transportModeCode: string | null, bookingInfo: unknown, contactInfo: unknown, remark: string | null, externalSource: string | null, externalId: string | null, dining: Record<string, unknown> | null, accommodation: Record<string, unknown> | null, sortOrder: number, version: number, createdAt: string, updatedAt: string, deletedAt: string | null }} ItineraryItem */
/** @typedef {{ code: string, label: string, aliases?: string[], icon?: string, color?: string, lineStyle?: string }} ReferenceEntry */
/** @typedef {{ currencies: ReferenceEntry[], costCategories: ReferenceEntry[], transportModes: ReferenceEntry[], currencyAliases: Record<string, string> }} ReferenceData */
/** @typedef {{ field: string, message: string }} FieldError */
/** @typedef {{ type: string, title: string, status: number, code: string, traceId: string, errors: FieldError[], detail?: string, instance?: string }} ProblemDetails */

export const generatedOpenApiSha256 = "${hash}";

/** @param {unknown} value @param {string} name @returns {Record<string, unknown>} */
function asObject(value, name) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(\`\${name} must be an object\`);
  }
  return /** @type {Record<string, unknown>} */ (value);
}

/** @param {unknown} value @returns {ExampleResource} */
export function parseExampleResponse(value) {
  const object = asObject(value, "ExampleResource");
  if (typeof object.id !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(object.id)) {
    throw new TypeError("ExampleResource.id must be a UUID");
  }
  if (typeof object.date !== "string" || !/^\\d{4}-\\d{2}-\\d{2}$/u.test(object.date)) {
    throw new TypeError("ExampleResource.date must be YYYY-MM-DD");
  }
  return { id: object.id, date: object.date };
}

/** @param {unknown} value @returns {Trip} */
export function parseTripResponse(value) {
  const object = asObject(value, "Trip");
  for (const field of ["id", "ownerId", "name", "startDate", "endDate", "defaultCurrency", "timezone", "mapProfile", "status", "createdAt", "updatedAt"]) {
    if (typeof object[field] !== "string" || object[field].length === 0) {
      throw new TypeError(\`Trip.\${field} must be a non-empty string\`);
    }
  }
  if (!/^\\d{4}-\\d{2}-\\d{2}$/u.test(String(object.startDate)) || !/^\\d{4}-\\d{2}-\\d{2}$/u.test(String(object.endDate))) {
    throw new TypeError("Trip dates must be YYYY-MM-DD");
  }
  if (!["cn_primary", "international_primary", "hybrid"].includes(String(object.mapProfile))) {
    throw new TypeError("Trip.mapProfile is invalid");
  }
  if (!["draft", "active", "archived", "deleted"].includes(String(object.status))) {
    throw new TypeError("Trip.status is invalid");
  }
  for (const field of ["totalDays", "travelers", "version"]) {
    if (!Number.isSafeInteger(object[field]) || Number(object[field]) < 1) {
      throw new TypeError(\`Trip.\${field} must be a positive integer\`);
    }
  }
  if (!Array.isArray(object.destinations)) throw new TypeError("Trip.destinations must be an array");
  const destinations = object.destinations.map((value) => {
    const destination = asObject(value, "Destination");
    if (typeof destination.id !== "string" || typeof destination.name !== "string") {
      throw new TypeError("Destination id and name must be strings");
    }
    if (!Number.isSafeInteger(destination.sortOrder) || Number(destination.sortOrder) < 0) {
      throw new TypeError("Destination.sortOrder must be a non-negative integer");
    }
    if (typeof destination.createdAt !== "string" || typeof destination.updatedAt !== "string") {
      throw new TypeError("Destination timestamps must be strings");
    }
    for (const field of ["countryCode", "city", "region"]) {
      if (destination[field] !== null && typeof destination[field] !== "string") {
        throw new TypeError(\`Destination.\${field} must be a string or null\`);
      }
    }
    return {
      id: destination.id,
      name: destination.name,
      countryCode: /** @type {string | null} */ (destination.countryCode),
      city: /** @type {string | null} */ (destination.city),
      region: /** @type {string | null} */ (destination.region),
      sortOrder: Number(destination.sortOrder),
      createdAt: destination.createdAt,
      updatedAt: destination.updatedAt,
    };
  });
  return {
    id: /** @type {string} */ (object.id),
    ownerId: /** @type {string} */ (object.ownerId),
    name: /** @type {string} */ (object.name),
    startDate: /** @type {string} */ (object.startDate),
    endDate: /** @type {string} */ (object.endDate),
    totalDays: Number(object.totalDays),
    travelers: Number(object.travelers),
    defaultCurrency: /** @type {string} */ (object.defaultCurrency),
    budget: typeof object.budget === "string" ? object.budget : null,
    timezone: /** @type {string} */ (object.timezone),
    mapProfile: /** @type {Trip["mapProfile"]} */ (object.mapProfile),
    description: typeof object.description === "string" ? object.description : null,
    status: /** @type {Trip["status"]} */ (object.status),
    version: Number(object.version),
    createdAt: /** @type {string} */ (object.createdAt),
    updatedAt: /** @type {string} */ (object.updatedAt),
    deletedAt: typeof object.deletedAt === "string" ? object.deletedAt : null,
    destinations,
  };
}

/** @param {unknown} value @returns {TripPage} */
export function parseTripPageResponse(value) {
  const object = asObject(value, "TripPage");
  if (!Array.isArray(object.items)) throw new TypeError("TripPage.items must be an array");
  if (object.nextCursor !== null && typeof object.nextCursor !== "string") {
    throw new TypeError("TripPage.nextCursor must be a string or null");
  }
  return {
    items: object.items.map(parseTripResponse),
    nextCursor: /** @type {string | null} */ (object.nextCursor),
  };
}

/** @param {unknown} value @returns {ItineraryItem} */
export function parseItineraryItemResponse(value) {
  const object = asObject(value, "ItineraryItem");
  for (const field of ["id", "tripId", "ownerId", "tripDayId", "itemType", "timeKind", "createdAt", "updatedAt"]) {
    if (typeof object[field] !== "string" || object[field].length === 0) {
      throw new TypeError(\`ItineraryItem.\${field} must be a non-empty string\`);
    }
  }
  if (!["activity", "attraction", "dining", "hotel", "transport", "other"].includes(String(object.itemType))) {
    throw new TypeError("ItineraryItem.itemType is invalid");
  }
  if (!["clock", "range", "period", "unscheduled"].includes(String(object.timeKind))) {
    throw new TypeError("ItineraryItem.timeKind is invalid");
  }
  if (!Number.isSafeInteger(object.sortOrder) || Number(object.sortOrder) < 0) {
    throw new TypeError("ItineraryItem.sortOrder must be a non-negative integer");
  }
  if (!Number.isSafeInteger(object.version) || Number(object.version) < 1) {
    throw new TypeError("ItineraryItem.version must be a positive integer");
  }
  if (object.endDayOffset !== 0 && object.endDayOffset !== 1) {
    throw new TypeError("ItineraryItem.endDayOffset must be 0 or 1");
  }
  for (const field of ["startTime", "endTime"]) {
    if (object[field] !== null && (typeof object[field] !== "string" || !/^([01]\\d|2[0-3]):[0-5]\\d$/u.test(object[field]))) {
      throw new TypeError(\`ItineraryItem.\${field} must be HH:mm or null\`);
    }
  }
  for (const field of ["dining", "accommodation"]) {
    if (object[field] !== null) asObject(object[field], \`ItineraryItem.\${field}\`);
  }
  return /** @type {ItineraryItem} */ (object);
}

/** @param {unknown} value @returns {ReferenceData} */
export function parseReferenceDataResponse(value) {
  const object = asObject(value, "ReferenceData");
  /** @param {unknown} entries @param {string} name @param {boolean} visual */
  const parseEntries = (entries, name, visual) => {
    if (!Array.isArray(entries)) throw new TypeError(\`\${name} must be an array\`);
    return entries.map((entry) => {
      const parsed = asObject(entry, \`\${name} entry\`);
      if (typeof parsed.code !== "string" || typeof parsed.label !== "string") {
        throw new TypeError(\`\${name} code and label must be strings\`);
      }
      if (parsed.aliases !== undefined && (!Array.isArray(parsed.aliases) || parsed.aliases.some((alias) => typeof alias !== "string"))) {
        throw new TypeError(\`\${name} aliases must be strings\`);
      }
      if (visual && (typeof parsed.icon !== "string" || !/^#[0-9A-F]{6}$/u.test(String(parsed.color)))) {
        throw new TypeError(\`\${name} visual fields are invalid\`);
      }
      if (name === "transportModes" && !["solid", "dashed", "dotted"].includes(String(parsed.lineStyle))) {
        throw new TypeError("transportModes lineStyle is invalid");
      }
      return {
        code: parsed.code,
        label: parsed.label,
        ...(Array.isArray(parsed.aliases) ? { aliases: /** @type {string[]} */ (parsed.aliases) } : {}),
        ...(typeof parsed.icon === "string" ? { icon: parsed.icon } : {}),
        ...(typeof parsed.color === "string" ? { color: parsed.color } : {}),
        ...(typeof parsed.lineStyle === "string" ? { lineStyle: parsed.lineStyle } : {}),
      };
    });
  };
  const aliases = asObject(object.currencyAliases, "currencyAliases");
  if (Object.values(aliases).some((alias) => typeof alias !== "string")) {
    throw new TypeError("currencyAliases values must be strings");
  }
  return {
    currencies: parseEntries(object.currencies, "currencies", false),
    costCategories: parseEntries(object.costCategories, "costCategories", true),
    transportModes: parseEntries(object.transportModes, "transportModes", true),
    currencyAliases: /** @type {Record<string, string>} */ (aliases),
  };
}

/** @param {unknown} value @returns {ProblemDetails} */
export function parseProblemDetails(value) {
  const object = asObject(value, "ProblemDetails");
  for (const field of ["type", "title", "code", "traceId"]) {
    if (typeof object[field] !== "string" || object[field].length === 0) {
      throw new TypeError(\`ProblemDetails.\${field} must be a non-empty string\`);
    }
  }
  if (!Number.isInteger(object.status) || typeof object.status !== "number" || object.status < 400 || object.status > 599) {
    throw new TypeError("ProblemDetails.status must be an HTTP error status");
  }
  if (!Array.isArray(object.errors)) {
    throw new TypeError("ProblemDetails.errors must be an array");
  }
  return {
    type: /** @type {string} */ (object.type),
    title: /** @type {string} */ (object.title),
    status: object.status,
    code: /** @type {string} */ (object.code),
    traceId: /** @type {string} */ (object.traceId),
    errors: object.errors.map((error) => {
      const fieldError = asObject(error, "FieldError");
      if (typeof fieldError.field !== "string" || typeof fieldError.message !== "string") {
        throw new TypeError("FieldError fields must be strings");
      }
      return { field: fieldError.field, message: fieldError.message };
    }),
    ...(typeof object.detail === "string" ? { detail: object.detail } : {}),
    ...(typeof object.instance === "string" ? { instance: object.instance } : {}),
  };
}

export class ApiProblemError extends Error {
  /** @param {ProblemDetails} problem */
  constructor(problem) {
    super(problem.title);
    this.name = "ApiProblemError";
    this.problem = problem;
  }
}

export class OnTheRoadClient {
  /** @param {string} baseUrl @param {{ fetch?: typeof fetch }} [options] */
  constructor(baseUrl, options = {}) {
    this.baseUrl = baseUrl.replace(/\\/$/u, "");
    this.fetch = options.fetch ?? globalThis.fetch;
  }

  /** @param {string} [exampleId] @returns {Promise<{ data: ExampleResource, etag: string | null }>} */
  async getExample(exampleId) {
    const suffix = exampleId ? \`/example/\${encodeURIComponent(exampleId)}\` : "/example";
    const response = await this.fetch(\`\${this.baseUrl}/api/v1\${suffix}\`, {
      headers: { accept: "application/json, application/problem+json" },
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new ApiProblemError(parseProblemDetails(payload));
    }
    return { data: parseExampleResponse(payload), etag: response.headers.get("etag") };
  }

  /** @returns {Promise<{ data: ReferenceData }>} */
  async getReferenceData() {
    const response = await this.fetch(\`\${this.baseUrl}/api/v1/system/reference-data\`, {
      headers: { accept: "application/json, application/problem+json" },
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new ApiProblemError(parseProblemDetails(payload));
    }
    return { data: parseReferenceDataResponse(payload) };
  }

  /** @param {Record<string, unknown>} input @param {string} idempotencyKey */
  async createTrip(input, idempotencyKey) {
    return this.#tripRequest("/trips", {
      method: "POST",
      headers: { "content-type": "application/json", "idempotency-key": idempotencyKey },
      body: JSON.stringify(input),
    });
  }

  /** @param {string} tripId */
  async getTrip(tripId) {
    return this.#tripRequest(\`/trips/\${encodeURIComponent(tripId)}\`);
  }

  /** @param {{ search?: string, currency?: string, status?: string, limit?: number }} [filters] */
  async listTrips(filters = {}) {
    const query = new globalThis.URLSearchParams();
    for (const [key, value] of Object.entries(filters)) {
      if (value !== undefined) query.set(key, String(value));
    }
    const suffix = query.size ? \`?\${query}\` : "";
    const response = await this.fetch(\`\${this.baseUrl}/api/v1/trips\${suffix}\`, {
      headers: { accept: "application/json, application/problem+json" },
    });
    const payload = await response.json();
    if (!response.ok) throw new ApiProblemError(parseProblemDetails(payload));
    return { data: parseTripPageResponse(payload) };
  }

  /** @param {string} tripId @param {Record<string, unknown>} patch @param {number} version */
  async updateTrip(tripId, patch, version) {
    return this.#tripRequest(\`/trips/\${encodeURIComponent(tripId)}\`, {
      method: "PATCH",
      headers: { "content-type": "application/json", "if-match": String(version) },
      body: JSON.stringify(patch),
    });
  }

  /** @param {string} tripId @param {number} version */
  async deleteTrip(tripId, version) {
    return this.#tripRequest(\`/trips/\${encodeURIComponent(tripId)}\`, {
      method: "DELETE",
      headers: { "if-match": String(version) },
    });
  }

  /** @param {string} tripId @param {number} version */
  async restoreTrip(tripId, version) {
    return this.#tripRequest(\`/trips/\${encodeURIComponent(tripId)}/restore\`, {
      method: "POST",
      headers: { "if-match": String(version) },
    });
  }

  /** @param {string} tripId @param {string} tripDayId @param {Record<string, unknown>} input */
  async createItineraryItem(tripId, tripDayId, input) {
    return this.#itineraryRequest(
      \`/trips/\${encodeURIComponent(tripId)}/days/\${encodeURIComponent(tripDayId)}/itinerary-items\`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ...input, tripDayId }),
      },
    );
  }

  /** @param {string} tripId @param {string} tripDayId */
  async listItineraryItems(tripId, tripDayId) {
    const response = await this.fetch(
      \`\${this.baseUrl}/api/v1/trips/\${encodeURIComponent(tripId)}/days/\${encodeURIComponent(tripDayId)}/itinerary-items\`,
      { headers: { accept: "application/json, application/problem+json" } },
    );
    const payload = await response.json();
    if (!response.ok) throw new ApiProblemError(parseProblemDetails(payload));
    if (!Array.isArray(payload)) throw new TypeError("ItineraryItem list must be an array");
    return { data: payload.map(parseItineraryItemResponse) };
  }

  /** @param {string} tripId @param {string} itemId */
  async getItineraryItem(tripId, itemId) {
    return this.#itineraryRequest(
      \`/trips/\${encodeURIComponent(tripId)}/itinerary-items/\${encodeURIComponent(itemId)}\`,
    );
  }

  /** @param {string} tripId @param {string} itemId @param {Record<string, unknown>} patch @param {number} version */
  async updateItineraryItem(tripId, itemId, patch, version) {
    return this.#itineraryRequest(
      \`/trips/\${encodeURIComponent(tripId)}/itinerary-items/\${encodeURIComponent(itemId)}\`,
      {
        method: "PATCH",
        headers: { "content-type": "application/json", "if-match": String(version) },
        body: JSON.stringify(patch),
      },
    );
  }

  /** @param {string} tripId @param {string} itemId @param {number} version */
  async deleteItineraryItem(tripId, itemId, version) {
    return this.#itineraryRequest(
      \`/trips/\${encodeURIComponent(tripId)}/itinerary-items/\${encodeURIComponent(itemId)}\`,
      { method: "DELETE", headers: { "if-match": String(version) } },
    );
  }

  /** @param {string} tripId @param {string} itemId @param {string} targetTripDayId */
  async copyItineraryItem(tripId, itemId, targetTripDayId) {
    return this.#itineraryRequest(
      \`/trips/\${encodeURIComponent(tripId)}/itinerary-items/\${encodeURIComponent(itemId)}/copy\`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ targetTripDayId }),
      },
    );
  }

  /** @param {string} path @param {RequestInit} [init] */
  async #itineraryRequest(path, init) {
    const response = await this.fetch(\`\${this.baseUrl}/api/v1\${path}\`, {
      ...init,
      headers: {
        accept: "application/json, application/problem+json",
        ...init?.headers,
      },
    });
    const payload = await response.json();
    if (!response.ok) throw new ApiProblemError(parseProblemDetails(payload));
    return {
      data: parseItineraryItemResponse(payload),
      etag: response.headers.get("etag"),
    };
  }

  /** @param {string} path @param {RequestInit} [init] */
  async #tripRequest(path, init) {
    const response = await this.fetch(\`\${this.baseUrl}/api/v1\${path}\`, {
      ...init,
      headers: {
        accept: "application/json, application/problem+json",
        ...init?.headers,
      },
    });
    const payload = await response.json();
    if (!response.ok) throw new ApiProblemError(parseProblemDetails(payload));
    return { data: parseTripResponse(payload), etag: response.headers.get("etag") };
  }
}
`;
}

async function main() {
  const contract = await readContract();
  const baseline = await readContract(baselineUrl);
  assertBackwardCompatible(baseline, contract);
  const generated = generateClientSource(contract);

  if (process.argv.includes("--check")) {
    const committed = await readFile(outputUrl, "utf8");
    if (committed !== generated) {
      throw new Error("Generated client is stale. Run `pnpm --filter @on-the-road/contracts generate`.");
    }
    return;
  }
  await writeFile(outputUrl, generated);
}

const invokedPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : "";
if (import.meta.url === invokedPath) {
  await main();
}
